language: node_js
node_js:
  - node
branches:
  only:
    - master
script:
  - npm run clear
  - npm run fetch_data
  - npm run build
deploy:
  skip_cleanup: true
  provider: script
  script: node deploy.js
  on:
    branch: master
