language: node_js
node_js:
- "8"
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get -qq update
- sudo apt-get -qq install g++-4.8
env:
- CXX=g++-4.8
script:
- npm run clear
- npm run fetch_data
- npm run fetch_images
- npm run build
deploy:
- provider: s3
  skip_cleanup: true
  local_dir: build
  bucket: daigou.neekey.net
  region: ap-southeast-2
  access_key_id:
    secure: YECTKb9XaPljyHgAFfMfUcYB9TKLL++2AB7bsEkJyZ/tbe2WTpRSqWBWd977yR/p1f0+Uwv+xPlRTvOYxvR8iwOnfLyHp+57OlEsT+baA5r7paP25MrdjQxLD6AclUpekarZKmsykxvC8Ndu3BczlZajZG1bllKX/2wQP/tt0X1WaGKp6Wqnn3iOk8GQaDKaA7F0dYQDvzITH9KlDkGc48DHA2CGb89uvd0JOpH6/HCQof8GnrgoRBptowf0/mUT/L9TZ2jcQ0eQGRA3fDFXptm4ALQgP0k53SnTUdbOn6ons/8gX08+T5OB58LT6eLUFn0UKyuGzkcXQeKcPAaz/4q2WG7epfhAxr++BPk4oXszzk//hXeHpOpyzXtAQy7qXFeKOpnJNVGcq/vREWZyfNS2JfSnp/cHYdrLYxZQ/lYZNxZkfmpWyh5iGEU1CjFtH6xoSLbMB/O5+/l9KrO5UalU2IG5FkqJNCFRTgKA8JuquTA+8H9mASKyvS9OIp+wNKKjQzgw7W/jzhdLKeO3TpXMIqNuQKVvTCUti3G/g+S06kfj0/mcEXZHy/Y7bB4H+ovS/TPSmzbMW6KuVt6EJH9asv5tfRpK46uKba3T42zUupEiRmUd23mjyUihJWbI6Omi8IhgHIW6Bx++ecRO2Mk4KFLY4sjRhAb48dfIdAs=
  secret_access_key:
    secure: SRYkGKKBuAaqS1X0H9S11U/G0+TloD9sqBxCgd6kHwH50Rned/OcoC2vYy6qepapvhtPwXXSuP/2sBQ3Y3eTxGI86rYkKQ3mfrCH5tQKGHULxKHOqZ9je5IXPymcYr77KJvw5R978I+wAudCxkYkqsEdOAgONpkNx4/xqyaBsCK6Y5OJyjoCerww22Jt84WL33mA9I6eeZkX7BsMZ0X+vxTu9guphqKA+CCFIwqHbZXYu7YS+Ljr/3oAF6f0XmbKKEH32nMiJVMXhpGwjKEd11mqnOr3uu4gal3/3X17UQ92ao5Emwlfne+ftXbRuLcKesxHGDVyBZ5U/Zjd5R6ZTD3UhT7xoFTIOL2kQ7LGgR1VDmvnT7JMH5vHtlITL163MUrLwGdxqzHo0c3NUYzUf/uASlY4NOzvHE1OX7TC69sSnYUYBTeTMdfG/08maH29K3HSycftbkD7EhSR6sPUiu4wgPHSAyJlsHNJWlRJ2/5oXKdTer086mkGDJYwN8YU2nbJfYUvjD01s5UQ6yDiAZz12GMQz4I6fzeEt3Jw5Mrsry8ZksnY0u8VN2czMccZA+8WgXpEg/et3GBWmGQAOiCXOE6nTLLWu3l1RSWcS6HB2lKyPwg84p+WcF9arwNKKw8yAAQfk8ThOI4dYF7EJhs61QR5XOl7TBcBaQVybJM=
