language: node_js
node_js:
  - node
branches:
  only:
    - master
cache:
  directories:
  - node_modules # NPM packages
script:
  - npm run clear
  - npm run fetch_data
  - npm run fetch_images
  - npm run s3_data
  - npm run build
deploy:
  - provider: script
    skip_cleanup: true
    script: node deploy.js
    on:
      branch: master
  - provider: s3
    skip_cleanup: true
    access_key_id: AKIAIJR6BIZCFGQXJVLQ
    secret_access_key:
      secure: kT1T33NL0NE4pbhNRrQWGrSmCdKozJvQnZNjzIbwMHhGtUK5FdDPmr4q89s5KKYuelbJaKOTWdwaf/J/djOQ9W3NvlVxvf2l41SlWAM3lf57TpE8xww2dEzK+ycjJuUWNGsURTJzwavnF1d8H+3r4EBD2mGyHwEpE7yuIcPzLsahw7C35MBlvKPH+x7JAr8tBNpzQKqM1IISdg4mIEFzkFX25WPnWSKG/0473sMAyP6bURyYBj0k4VjkCXA0r6iKsXGkgVYCaA2jt/cpl9Lx50Mk+UNY9nSAExvWmWNaCeihYlivl10UiWYA81rayoAAfLHAJ7BucGnkTPveK32ponyxXgVToSRpzBxvuq/AVTVHKE48gqCE3Kr2M9T/SLA9oqUrrOqyPmb7184jSauP8WEF7o0C6Ozw2AEsMWyD2QKgtwl8Wns9FGnA4tz6m64Z4TsYqtca2jKgH1L1nfwjZo+CQD2gFTtLoCtpruDiO5BzctFEm4WDuY1oIblwtnt3Ci5q4QhFe9O/7VpI98vUW8fubjrm3CIusf38NYTJyJ0gU5aDJG7cPzaspGf+n5Mm5fp60w2r0RSsrBc99a+5qoXVZqsw7BUXPoYQtpX7TS9olPIF3UDTEMgjvewZZIWVQ8PPg02igg3uQTg4LCPVnQsbp2LVZmW37r8ph5f9l+I=
    bucket: neekey-daigou
    local-dir: s3build
    upload-dir: product
    acl: public_read
    region: ap-southeast-2
    on:
      repo: neekey/daigou
